#!/bin/sh
SEMPATH=../semparse
GRAMMAR=../cubesem/grammar/stacks.grammar
cd $SEMPATH
# java -ea -Dmodules=core,freebase,overnight -Xms8G -Xmx10G -cp libsempre/*:lib/* edu.stanford.nlp.sempre.Main -execDir state/execs/7.exec -overwriteExecDir -addToView 0 -JavaExecutor.convertNumberValues false -useAnchorsOnce true -trackLocalChoices -JoinFn.typeInference true -Builder.parser FloatingParser -FloatingParser.executeAllDerivations true -LanguageAnalyzer.lowerCaseTokens false -Learner.maxTrainIters 5 -Derivation.showUtterance -maxExamples train:MAX -FeatureExtractor.featureDomains denotation -FeatureExtractor.featureComputers cubeworld.CubeWorldFeatureComputer -CubeWorldFeatureComputer.featureDomains ngram context -coarsePrune -Params.l1Reg lazy -Params.l1RegCoeff 0.001 -Grammar.inPaths $GRAMMAR -Dataset.trainFrac 0.8 -Dataset.devFrac 0.2 -FloatingParser.maxDepth 9 -Parser.beamSize 20 -Dataset.inPaths train:../cubesem/data/train.examples test:../cubesem/data/test.examples

#use grammar tags: -Grammar.tags generate general

# elif [ $1 = "cube" ]; then  -FloatingParser.useSizeInsteadOfDepth true 
FLOAT_OPTS="-Parser FloatingParser -FloatingParser.maxDepth 9 -FloatingParser.useSizeInsteadOfDepth true"
TRAIN_IN="-Dataset.inPaths train:../cubesem/data/fullgame.json -Learner.maxTrainIters 1" #test:../cubesem/data/fullgame.json 
TRAIN_OUTS="-Master.newExamplesPath ../cubesem/data/fullgame.json -Master.newParamsPath ../cubesem/newparam"
# -Dataset.inPaths train:../cubesem/examples"
OPTIONS="-Dmodules=core,cubeworld -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive -JavaExecutor.convertNumberValues false -FeatureExtractor.featureDomains tree -FeatureExtractor.featureComputers cubeworld.StacksWorldFeatureComputer -StacksWorldFeatureComputer.ngramN 3 -Params.initStepSize 0.5 -Params.adaptiveStepSize true -Params.initWeightsRandomly false -Grammar.inPaths $GRAMMAR -Parser.pruneErrorValues true -Parser.beamSize 30 -JoinFn.typeInference true -LanguageAnalyzer.lowerCaseTokens true -Params.l1Reg lazy -Params.l1RegCoeff 0.001  -Server.numThreads 1"

# features are tree, heads, ngram
DEBUG="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8898"

rlwrap java $DEBUG $OPTIONS $FLOAT_OPTS $TRAIN_OUTS $TRAIN_IN "$@"
#" -Master.commands \"(context (graph NaiveKnowledgeGraph ((string [[0,0,0,1],[1,1,1,2],[2,2,2,0]]) (name b) (name c))))\""
#rlwrap java $OPTIONS_SIMPLE "$@"
