#!/bin/sh
SEMPATH=../semparse
GRAMMAR=../cubesem/grammar/stacks.grammar
cd $SEMPATH
# elif [ $1 = "cube" ]; then  -FloatingParser.useSizeInsteadOfDepth true 
LEARNOPTS="-Parser FloatingParser -FloatingParser.maxDepth 8 -FloatingParser.useSizeInsteadOfDepth true -Params.l1Reg lazy -Params.l1RegCoeff 0.001 -Parser.beamSize 50 -StacksWorldFeatureComputer.ngramN 3 -Params.initStepSize 1 -Params.adaptiveStepSize true"

SESSIONSTUFF="-Master.onlineLearnExamples false -Master.independentSessions true -Master.bePragmatic true -Session.smoothAlpha 1.0"

TRAIN_IN="-Dataset.inPaths train:../cubesem/data/validation.lisp -Learner.maxTrainIters 1"
#test:../cubesem/data/fullgame.json 
TRAIN_OUTS="-Master.newExamplesPath ../cubesem/data/validation.lisp"

# -Master.newParamsPath ../cubesem/validation.params
# -Dataset.inPaths train:../cubesem/examples"
OPTIONS="-Dmodules=core,cubeworld -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive -JavaExecutor.convertNumberValues false -FeatureExtractor.featureDomains tree -FeatureExtractor.featureComputers cubeworld.StacksWorldFeatureComputer  -Params.initWeightsRandomly false -Grammar.inPaths $GRAMMAR -Parser.pruneErrorValues true -JoinFn.typeInference true -LanguageAnalyzer.lowerCaseTokens true"

# features are tree, heads, ngram
DEBUG="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8898"

if [ "$HOSTNAME" = "jonsson.stanford.edu" ]; then
    echo "running on jonsson"
    TRAIN_OUTS_SERVER="-Master.newExamplesPath /afs/cs.stanford.edu/u/sidaw/git/examples/ -Master.logPath /afs/cs.stanford.edu/u/sidaw/git/logs/ -server true"
    echo rlwrap java $OPTIONS $LEARNOPTS $SESSIONSTUFF $TRAIN_OUTS_SERVER -Server.numThreads 16 "$@"
    rlwrap java $OPTIONS $LEARNOPTS $SESSIONSTUFF $TRAIN_OUTS_SERVER -Server.numThreads 16 "$@"
else
    echo "not running on jonsson"
    TRAIN_OUTS_LOCAL="-Master.newExamplesPath ../cubesem/examples/ -Master.logPath ../cubesem/logs/ -server true"
    rlwrap java $OPTIONS $LEARNOPTS $TRAIN_OUTS_LOCAL $SESSIONSTUFF -Server.numThreads 1 "$@"
fi
