#!/bin/sh
SEMPATH=../semparse
GRAMMAR=../cubesem/grammar/richer.floating.grammar
EXAMPLEPATH=~/shrdlurn/examples/
cd $SEMPATH
PARSEROPTS="-Parser FloatingParser -FloatingParser.maxDepth 12 -FloatingParser.useSizeInsteadOfDepth true -FloatingParser.defaultIsFloating true -FloatingParser.useAnchorsOnce true -Parser.pruneErrorValues true"
LEARNOPTS="-Params.l1Reg lazy -Params.l1RegCoeff 0.001 -Parser.beamSize 100 -Params.initStepSize 0.1 -Params.adaptiveStepSize true -ParserState.customExpectedCounts UNIFORM"
FEATOPTS="-FeatureExtractor.featureComputers cubeworld.RicherStacksWorldFeatureComputer -FeatureExtractor.featureDomains stats subtree RicherStacksWorldFeatureComputer.ngramN 4"




OPTIONS="-Dmodules=core,cubeworld -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main  -execDir _OUTPATH_/runRichmoreparams -overwriteExecDir -addToView 0 -Main.interactive -JavaExecutor.convertNumberValues false -Params.initWeightsRandomly false -Grammar.inPaths $GRAMMAR -Grammar.binarizeRules false -JoinFn.typeInference true -LanguageAnalyzer.lowerCaseTokens true"

# features are tree, heads, ngram
DEBUG="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8898"
TRAIN_OUTS_LOCAL_IND="-Master.newExamplesPath $EXAMPLEPATH  -Master.logPath ../cubesem/logs/"
INDEP_SESSIONS="-Master.onlineLearnExamples false -Master.independentSessions true"
SESSIONS="-Master.onlineLearnExamples true -Master.independentSessions false"

if [ "$1" = "train" ]; then
    TRAIN_IN="-Dataset.inPaths train:$EXAMPLEPATH/sidaw.lisp -Learner.maxTrainIters 1"
else
    TRAIN_IN=""
fi
   
echo "not running on jonsson"
rlwrap java $OPTIONS $PARSEROPTS $LEARNOPTS $FEATOPTS $SESSIONS $TRAIN_OUTS_LOCAL $TRAIN_IN -server true -Server.numThreads 1

