#!/bin/sh
SEMPATH=../semparse
GRAMMAR=../cubesem/grammar/cube.grammar
GRAMMARSIMPLE=../cubesem/grammar/simplecube.grammar
GRAMMARTOKENS=../cubesem/grammar/tokens.grammar
cd $SEMPATH

# elif [ $1 = "cube" ]; then

OPTIONS="-Dmodules=core,cubeworld -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive -JavaExecutor.convertNumberValues false -FeatureExtractor.featureDomains rule span ngram lemmaAndBinaries -FeatureExtractor.featureComputers cubeworld.CubeWorldFeatureComputer -Grammar.inPaths $GRAMMAR -Parser.pruneErrorValues true -Parser.beamSize 1000 -JoinFn.typeInference true -LanguageAnalyzer.lowerCaseTokens false -server true"

#-FeatureExtractor.useAllFeatures true

OPTIONS_SIMPLE="-Dmodules=core,cubeworld -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive -JavaExecutor.convertNumberValues false -FeatureExtractor.featureDomains rule bigram -Grammar.inPaths $GRAMMARSIMPLE -Parser.pruneErrorValues true -Parser.beamSize 1000 -JoinFn.typeInference true -LanguageAnalyzer.lowerCaseTokens false -server true -Parser FloatingParser"

OPTIONS_TOKENS="-Dmodules=core,cubeworld -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive -JavaExecutor.convertNumberValues false -FeatureExtractor.featureDomains rule span denotation -FeatureExtractor.featureComputers DerivOpCountFeatureComputer -Grammar.inPaths $GRAMMARTOKENS -Parser.pruneErrorValues true -Parser.beamSize 1000 -JoinFn.typeInference true -LanguageAnalyzer.lowerCaseTokens false -server true"

rlwrap java $OPTIONS "$@"
#rlwrap java $OPTIONS_SIMPLE "$@"
