const Actions = {
  TRY_QUERY: "TRY_QUERY",
  ACCEPT: "ACCEPT",
  DEFINE: "DEFINE",

  REFRESH_EXAMPLE: "REFRESH_EXAMPLE",

  REVERT: "REVERT",
  SET_STATUS: "SET_STATUS",
  SET_QUERY: "SET_QUERY",
  RESET_RESPONSES: "RESET_RESPONSES",

  OPEN_DEFINE: "OPEN_DEFINE",
  CLOSE_DEFINE: "CLOSE_DEFINE",
  SET_PIN: "SET_PIN",
  REMOVE_PIN: "REMOVE_PIN",
  MARK_PIN: "MARK_PIN",
  INJECT_PIN: "INJECT_PIN",
  SET_DEFINE_N: "SET_DEFINE_N",
  REMOVE_LAST: "REMOVE_LAST",

  SESSION_ID: "SESSION_ID",

  OPEN_LOGGING_SOCKET: "OPEN_LOGGING_SOCKET",
  LOAD_COMMUNITY_STRUCTS: "LOAD_COMMUNITY_STRUCTS",
  SHARED_STRUCT: "SHARED_STRUCT",
  NEW_UPVOTE: "NEW_UPVOTE"
}

export default Actions
