const Actions = {
  TRY_QUERY: "TRY_QUERY",
  ACCEPT: "ACCEPT",
  DEFINE: "DEFINE",

  REVERT: "REVERT",
  SET_STATUS: "SET_STATUS",
  SET_QUERY: "SET_QUERY",
  RESET_RESPONSES: "RESET_RESPONSES",

  OPEN_DEFINE: "OPEN_DEFINE",
  CLOSE_DEFINE: "CLOSE_DEFINE",
  SET_PIN: "SET_PIN",
  REMOVE_PIN: "REMOVE_PIN",
  MARK_PIN: "MARK_PIN",
  INJECT_PIN: "INJECT_PIN",
  SET_DEFINE_N: "SET_DEFINE_N",
  REMOVE_LAST: "REMOVE_LAST",

  SET_SESSION_ID: "SET_SESSION_ID",

  OPEN_LOGGING_SOCKET: "OPEN_LOGGING_SOCKET",
  SHARED_STRUCT: "SHARED_STRUCT",
  NEW_ACCEPT: "NEW_ACCEPT",
  NEW_UPVOTE: "NEW_UPVOTE",
  NEW_DEFINE: "NEW_DEFINE",
  NEW_STRUCT: "NEW_STRUCT",
  NEW_UTTERANCES: "NEW_UTTERANCES",

  SET_TASK: "SET_TASK",

  CLEAR: "CLEAR"
}

export default Actions
