const Actions = {
  TRY_QUERY: "TRY_QUERY",
  ACCEPT: "ACCEPT",
  DEFINE: "DEFINE",

  REFRESH_EXAMPLE: "REFRESH_EXAMPLE",

  REVERT: "REVERT",
  SET_STATUS: "SET_STATUS",
  SET_QUERY: "SET_QUERY",
  RESET_RESPONSES: "RESET_RESPONSES",

  OPEN_DEFINE: "OPEN_DEFINE",
  CLOSE_DEFINE: "CLOSE_DEFINE",
  SET_PIN: "SET_PIN",
  REMOVE_PIN: "REMOVE_PIN",

  SESSION_ID: "SESSION_ID"
}

export default Actions
